---
name: CI ROS 2 images

on:
  pull_request:
    paths:
    - '.ci/**'
    - '.github/workflows/ros2_ci.yaml'
    - 'ros2/nightly/**'
    - 'ros2/source/**'
  push:
    branches-ignore:
    - 'master'
    paths:
    - '.ci/**'
    - '.github/workflows/ros2_ci.yaml'
    - 'ros2/nightly/**'
    - 'ros2/source/**'
jobs:
  build_images:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {HUB_REPO: ros2, HUB_RELEASE: source}
          - {HUB_REPO: ros2, HUB_RELEASE: nightly}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check and build ROS 2 image
        env: ${{matrix.env}}
        run: |
          cd $HUB_REPO/$HUB_RELEASE
          make build
